---
# tasks file for controlplane
- name: Debian prepere
  import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: Install containerd
  import_tasks: containerd.yaml

- name: Install k8s
  import_tasks: k8s.yaml