---
# tasks file for k8s/install
- name: Debian prepere
  import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- name: aarch64 prepere
  import_tasks: aarch64.yaml
  when: ansible_facts['architecture'] == "aarch64"

- name: Install containerd
  import_tasks: containerd.yaml

- name: Install k8s
  import_tasks: k8s.yaml