---
# tasks file for worker
- name: Join cluster
  ansible.builtin.import_role:
    name: k8s/join
  vars:
    cp_ip: "{{ k8s_cp_leader_ip }}"
    wk_ip: "{{ ansible_os_ip }}"
    lb_ip: "{{ k8s_ha_ip }}"
